import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import {
  ArrowRight,
  BarChart3,
  CheckCircle2,
  ShieldCheck,
  Users,
  Zap,
  Link2,
  Sparkles,
  DollarSign,
  TrendingUp,
  CreditCard,
  Building2,
  ChevronDown,
  Award,
  Lock,
  Smartphone,
  Gift,
  Star,
  Check,
} from 'lucide-react';
import { ROUTES } from '../constants/routes';
import veggieLogo from '../assets/veggie-radiance-logo.svg';
import '../styles/components.css';

const bentoFeatures = [
  {
    icon: Zap,
    tag: 'Instant Tracking',
    title: 'Real-Time Attribution Engine',
    text: 'Every click, coupon usage, and sale is recorded synchronously with cookie-backed 30-day persistence.',
  },
  {
    icon: Users,
    tag: 'Team Leadership',
    title: 'Multi-Tier Team Overrides',
    text: 'Super Affiliates automatically earn secondary commissions (5% to 7%) on every sale generated by their recruited team.',
  },
  {
    icon: ShieldCheck,
    tag: 'Bank Security',
    title: 'Instant Payouts & Maker-Checker',
    text: 'Seamless bank transfer & UPI payouts backed by high-threshold admin maker-checker audit verification.',
  },
  {
    icon: BarChart3,
    tag: 'Analytics Funnel',
    title: 'Deep Conversion Reports',
    text: 'Monitor click-through rates, active campaigns, order values, and commission pipelines from one unified dashboard.',
  },
  {
    icon: Gift,
    tag: 'Storefront SDK',
    title: 'Auto 10% Storefront Discount',
    text: 'Our embeddable SDK auto-applies partner discount codes at checkout without customer friction.',
  },
  {
    icon: Smartphone,
    tag: 'Mobile Ready',
    title: 'Capacitor Android Native App',
    text: 'Track commissions, request payouts, and monitor your referral team on the move with full mobile support.',
  },
];

const faqs = [
  {
    q: 'How does the Veggie Referral Link tracking work?',
    a: 'When someone clicks your referral link, our storefront SDK records your unique code in their browser cookies for 30 days. When they complete a purchase, your commission is automatically calculated and credited to your wallet.',
  },
  {
    q: 'What is the difference between an Affiliate and a Super Affiliate?',
    a: 'Standard Affiliates earn direct commissions (10%) on shopping orders. Super Affiliates can recruit a team of sub-affiliates and earn an additional 5% to 7% secondary commission on all team sales.',
  },
  {
    q: 'How fast do I get paid for my earnings?',
    a: 'You can request a withdrawal to your registered Bank Account or UPI ID anytime your wallet balance exceeds the minimum threshold. Approved withdrawals are processed within 24 to 48 hours.',
  },
  {
    q: 'Can I integrate Veggie with my own e-commerce store?',
    a: 'Yes! Veggie provides a lightweight JS script (`veggie-storefront-discount.js`) that takes less than 2 minutes to embed on your website.',
  },
];

export const Landing = () => {
  const [calcReferrals, setCalcReferrals] = useState(40);
  const [openFaq, setOpenFaq] = useState(0);

  // Commission Calculator Math (Assuming avg order ₹1,500 @ 10% direct + 5% team)
  const avgOrderValue = 1500;
  const directCommissionRate = 0.10; // 10%
  const teamCommissionRate = 0.05;   // 5%
  
  const directEarnings = Math.round(calcReferrals * avgOrderValue * directCommissionRate);
  const teamEstimate = Math.round(calcReferrals * 0.5 * avgOrderValue * teamCommissionRate);
  const totalMonthlyEarnings = directEarnings + teamEstimate;

  return (
    <main className="landing-page-v2">
      {/* Ambient Lighting Orbs */}
      <div className="v2-glow v2-glow-1" aria-hidden="true" />
      <div className="v2-glow v2-glow-2" aria-hidden="true" />
      <div className="v2-glow v2-glow-3" aria-hidden="true" />

      {/* Top Glassmorphic Navigation Header */}
      <header className="landing-nav-v2">
        <div className="nav-container-v2">
          <Link className="landing-brand-v2" to="/">
            <img className="landing-brand-logo-v2" src={veggieLogo} alt="VEGGIE Affiliate Network" fetchPriority="high" loading="eager" />
          </Link>

          <nav className="nav-links-v2">
            <a href="#features">Features</a>
            <a href="#calculator">Earnings Calculator</a>
            <a href="#roles">Partner Tiers</a>
            <a href="#faq">FAQ</a>
          </nav>

          <div className="nav-actions-v2">
            <Link className="btn-nav-ghost" to={ROUTES.LOGIN}>Sign In</Link>
            <Link className="btn-nav-emerald" to={ROUTES.REGISTER}>
              Join Network <ArrowRight size={15} />
            </Link>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="landing-hero-v2" aria-label="Welcome banner">
        <div className="hero-grid-v2">
          {/* Left Copy */}
          <div className="hero-copy-v2">
            <div className="hero-eyebrow-v2">
              <Sparkles size={14} className="eyebrow-icon-v2" />
              <span>#1 Next-Gen Organic & E-Commerce Affiliate Platform</span>
            </div>

            <h1 className="landing-hero-heading-v2">
              Grow with <span className="text-gradient-emerald">VEGGIE</span> affiliate network
            </h1>

            <p className="hero-subtext-v2">
              Empower your audience, lead high-performing partner teams, and unlock predictable monthly revenue with real-time conversion tracking, automated 10% storefront discounts, and instant bank payouts.
            </p>

            <div className="hero-ctas-v2">
              <Link className="landing-cta landing-cta-primary btn-hero-emerald" to={ROUTES.REGISTER}>
                Become an affiliate <ArrowRight size={18} />
              </Link>
              <Link className="btn-hero-glass" to={ROUTES.LOGIN}>
                <Lock size={16} /> Partner Portal Sign In
              </Link>
            </div>

            {/* Social Trust Metrics Bar */}
            <div className="hero-trust-bar-v2">
              <div className="trust-item-v2">
                <CheckCircle2 size={16} className="trust-icon-v2" />
                <span><strong>10,000+</strong> Active Affiliates</span>
              </div>
              <div className="trust-item-v2">
                <CheckCircle2 size={16} className="trust-icon-v2" />
                <span><strong>₹1.5 Cr+</strong> Paid in Commissions</span>
              </div>
              <div className="trust-item-v2">
                <CheckCircle2 size={16} className="trust-icon-v2" />
                <span><strong>99.9%</strong> Tracking Accuracy</span>
              </div>
            </div>
          </div>

          {/* Right Visual Stage Mockup */}
          <div className="hero-stage-v2" aria-label="VEGGIE dashboard preview">
            <div className="hero-stage-glow" />
            
            {/* Dashboard Card Preview */}
            <div className="v2-dash-mockup">
              <div className="dash-mockup-header">
                <div className="dash-mockup-dots">
                  <span className="dot dot-red" />
                  <span className="dot dot-yellow" />
                  <span className="dot dot-green" />
                </div>
                <div className="dash-mockup-title">
                  <Sparkles size={13} /> Veggie Partner Portal
                </div>
                <span className="dash-mockup-live">
                  <span className="live-pulse-dot" /> LIVE
                </span>
              </div>

              <div className="dash-mockup-body">
                <div className="dash-stat-primary">
                  <div>
                    <span className="stat-label-sub">Monthly Wallet Balance</span>
                    <h3 className="stat-value-emerald">₹48,920.00</h3>
                  </div>
                  <div className="stat-pill-growth">
                    <TrendingUp size={14} /> +34.2%
                  </div>
                </div>

                {/* Animated Conversion Ticker */}
                <div className="dash-live-ticker">
                  <Zap size={14} className="ticker-icon" />
                  <div className="ticker-text">
                    <strong>New Commission Earned!</strong>
                    <span>Order #8942 · ₹650.00 credited</span>
                  </div>
                  <span className="ticker-time">Just now</span>
                </div>

                {/* Visual Chart Bars */}
                <div className="dash-chart-bars">
                  <div className="chart-bar-item"><span style={{ height: '40%' }} /><small>M</small></div>
                  <div className="chart-bar-item"><span style={{ height: '65%' }} /><small>T</small></div>
                  <div className="chart-bar-item"><span style={{ height: '50%' }} /><small>W</small></div>
                  <div className="chart-bar-item"><span style={{ height: '85%' }} /><small>T</small></div>
                  <div className="chart-bar-item"><span style={{ height: '70%' }} /><small>F</small></div>
                  <div className="chart-bar-item"><span style={{ height: '95%' }} /><small>S</small></div>
                  <div className="chart-bar-item active-bar"><span style={{ height: '100%' }} /><small>S</small></div>
                </div>

                <div className="dash-metrics-grid">
                  <div className="metric-box">
                    <small>Total Referrals</small>
                    <strong>12,840</strong>
                  </div>
                  <div className="metric-box">
                    <small>Conversions</small>
                    <strong>1,124</strong>
                  </div>
                  <div className="metric-box">
                    <small>Team Members</small>
                    <strong>+28 Active</strong>
                  </div>
                </div>
              </div>
            </div>

            {/* Floating Glass Pills */}
            <div className="floating-pill-v2 pill-top-left">
              <Users size={16} className="pill-icon-lime" />
              <div>
                <strong>+28 Partners</strong>
                <small>Super Affiliate Network</small>
              </div>
            </div>

            <div className="floating-pill-v2 pill-bottom-right">
              <DollarSign size={16} className="pill-icon-emerald" />
              <div>
                <strong>₹1,280.00</strong>
                <small>Direct Commission Earned</small>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Interactive Earnings Calculator Section */}
      <section id="calculator" className="v2-section landing-calc-section">
        <div className="v2-container">
          <div className="section-header-v2">
            <span className="section-badge-v2">💰 REVENUE POTENTIAL</span>
            <h2>Calculate Your Monthly Earnings</h2>
            <p>See how much you can earn as a Veggie Affiliate partner based on your referral reach.</p>
          </div>

          <div className="calc-card-v2">
            <div className="calc-inputs-v2">
              <div className="slider-header-v2">
                <label htmlFor="referralSlider">Estimated Monthly Referral Sales:</label>
                <span className="slider-counter-v2">{calcReferrals} Orders / month</span>
              </div>
              <input
                id="referralSlider"
                type="range"
                min="5"
                max="300"
                step="5"
                value={calcReferrals}
                onChange={(e) => setCalcReferrals(Number(e.target.value))}
                className="calc-range-slider"
              />

              <div className="calc-assumptions-v2">
                <div><Check size={14} /> Avg. Order Value: ₹1,500</div>
                <div><Check size={14} /> Direct Commission: 10%</div>
                <div><Check size={14} /> Team Override: Up to 7%</div>
              </div>
            </div>

            <div className="calc-results-v2">
              <span className="result-label-v2">Estimated Monthly Income</span>
              <h3 className="result-amount-v2">₹{totalMonthlyEarnings.toLocaleString('en-IN')}</h3>
              <p className="result-breakdown-v2">
                Includes <strong>₹{directEarnings.toLocaleString('en-IN')}</strong> direct commissions + <strong>₹{teamEstimate.toLocaleString('en-IN')}</strong> estimated team bonuses.
              </p>
              <Link to={ROUTES.REGISTER} className="btn-hero-emerald btn-full-width">
                Start Earning Today <ArrowRight size={16} />
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Bento Grid Feature Showcase */}
      <section id="features" className="v2-section">
        <div className="v2-container">
          <div className="section-header-v2">
            <span className="section-badge-v2">⚡ BUILT FOR SCALE</span>
            <h2>Everything You Need To Grow</h2>
            <p>Enterprise-grade tools engineered specifically for high-performing affiliates and team leaders.</p>
          </div>

          <div className="landing-bento-grid">
            {bentoFeatures.map(({ icon: Icon, tag, title, text }, idx) => (
              <article key={title} className={`bento-card-v2 bento-card-${idx + 1}`}>
                <div className="bento-icon-box">
                  <Icon size={22} />
                </div>
                <span className="bento-tag">{tag}</span>
                <h3>{title}</h3>
                <p>{text}</p>
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* Account Tier Comparison (Super Affiliate vs Standard) */}
      <section id="roles" className="v2-section landing-tiers-section">
        <div className="v2-container">
          <div className="section-header-v2">
            <span className="section-badge-v2">👑 PARTNER TIERS</span>
            <h2>Choose Your Path To Growth</h2>
            <p>Whether you are an independent influencer or a team builder, Veggie has the perfect program for you.</p>
          </div>

          <div className="tiers-grid-v2">
            {/* Super Affiliate Card (Featured) */}
            <article className="tier-card-v2 tier-card-featured">
              <div className="tier-badge-featured">⭐ MOST POPULAR FOR TEAMS</div>
              <div className="tier-header-v2">
                <div className="tier-icon-circle"><Users size={24} /></div>
                <h3>Super Affiliate</h3>
                <p>For community leaders & team builders</p>
              </div>

              <div className="tier-highlight-v2">
                <span className="highlight-num">10% + 7%</span>
                <span className="highlight-desc">Direct Shopping Commission + Recruitment Team Overrides</span>
              </div>

              <ul className="tier-checklist-v2">
                <li><Check size={16} /> Everything in Standard Affiliate</li>
                <li><Check size={16} /> Recruit & manage unlimited sub-affiliates</li>
                <li><Check size={16} /> Earn 5% (1-15 members) to 7% (16+ members) team bonuses</li>
                <li><Check size={16} /> Dedicated Team Analytics Dashboard</li>
                <li><Check size={16} /> Priority Bank Withdrawal Processing</li>
              </ul>

              <Link to={ROUTES.REGISTER} className="btn-hero-emerald btn-full-width">
                Join as Super Affiliate <ArrowRight size={16} />
              </Link>
            </article>

            {/* Standard Affiliate Card */}
            <article className="tier-card-v2">
              <div className="tier-header-v2">
                <div className="tier-icon-circle"><Link2 size={24} /></div>
                <h3>Standard Affiliate</h3>
                <p>For creators & independent promoters</p>
              </div>

              <div className="tier-highlight-v2">
                <span className="highlight-num">10% Direct</span>
                <span className="highlight-desc">Flat Direct Shopping Commission per referral sale</span>
              </div>

              <ul className="tier-checklist-v2">
                <li><Check size={16} /> Instant unique referral link generation</li>
                <li><Check size={16} /> 10% Auto-discount code for your followers</li>
                <li><Check size={16} /> Real-time click & conversion tracking</li>
                <li><Check size={16} /> Wallet earnings & direct bank payouts</li>
                <li><Check size={16} /> High-converting marketing banners</li>
              </ul>

              <Link to={ROUTES.REGISTER} className="btn-hero-glass btn-full-width">
                Join as Standard Affiliate <ArrowRight size={16} />
              </Link>
            </article>
          </div>
        </div>
      </section>

      {/* Live Storefront Auto-Discount SDK Preview */}
      <section className="v2-section landing-storefront-demo">
        <div className="v2-container">
          <div className="storefront-card-v2">
            <div className="storefront-info-v2">
              <span className="section-badge-v2">🛒 Frictionless Checkout</span>
              <h2>Automated 10% Storefront Discount Banner</h2>
              <p>
                When shoppers click your referral link (`?ref=YOUR_CODE`), our storefront script automatically displays a 10% partner banner and auto-applies your discount coupon at checkout.
              </p>
              <div className="storefront-bullets-v2">
                <div><CheckCircle2 size={16} className="bullet-icon-emerald" /> 30-Day Cookie Retention</div>
                <div><CheckCircle2 size={16} className="bullet-icon-emerald" /> Zero manual coupon typing required</div>
              </div>
            </div>

            <div className="storefront-mock-v2">
              <div className="mock-banner-preview">
                <span>🎉 10% Veggie Partner Discount Active! Code: <code>VEGGIE10</code></span>
              </div>
              <div className="mock-product-box">
                <div className="mock-prod-img" />
                <div className="mock-prod-meta">
                  <strong>Organic Organic Veggie Bundle</strong>
                  <div className="mock-price-tag">
                    <span className="price-old">₹1,500.00</span>
                    <span className="price-new">₹1,350.00</span>
                    <span className="price-badge-10">10% OFF</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section id="faq" className="v2-section landing-faq-section">
        <div className="v2-container">
          <div className="section-header-v2">
            <span className="section-badge-v2">❓ FAQ</span>
            <h2>Frequently Asked Questions</h2>
            <p>Have questions? We have answers to help you get started quickly.</p>
          </div>

          <div className="faq-list-v2">
            {faqs.map((faq, idx) => {
              const isOpen = openFaq === idx;
              return (
                <div key={idx} className={`faq-item-v2 ${isOpen ? 'faq-item-open' : ''}`}>
                  <button
                    className="faq-trigger-v2"
                    type="button"
                    onClick={() => setOpenFaq(isOpen ? -1 : idx)}
                  >
                    <span>{faq.q}</span>
                    <ChevronDown size={18} className={`faq-chevron ${isOpen ? 'rotate-180' : ''}`} />
                  </button>
                  {isOpen && <div className="faq-answer-v2">{faq.a}</div>}
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Bottom High-Impact CTA Banner */}
      <section className="v2-section landing-footer-cta">
        <div className="v2-container">
          <div className="cta-banner-card-v2">
            <h2>Ready To Scale Your Affiliate Income?</h2>
            <p>Join thousands of successful partners growing their business with Veggie Affiliate Network today.</p>
            <div className="banner-actions-v2">
              <Link to={ROUTES.REGISTER} className="btn-hero-emerald btn-large">
                Create Free Partner Account <ArrowRight size={18} />
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Modern Dark Emerald Footer */}
      <footer className="landing-footer-v2">
        <div className="v2-container footer-grid-v2">
          <div className="footer-brand-col">
            <img src={veggieLogo} alt="VEGGIE Affiliate" className="footer-logo-v2" />
            <p>The premier affiliate SaaS network powering organic produce & e-commerce partner growth.</p>
          </div>

          <div className="footer-links-col">
            <strong>Platform</strong>
            <a href="#features">Features</a>
            <a href="#calculator">Earnings Calculator</a>
            <a href="#roles">Partner Tiers</a>
            <Link to={ROUTES.LOGIN}>Partner Login</Link>
          </div>

          <div className="footer-links-col">
            <strong>Account</strong>
            <Link to={ROUTES.REGISTER}>Become a Partner</Link>
            <Link to={ROUTES.REGISTER}>Join Super Affiliate</Link>
            <Link to={ROUTES.LOGIN}>Dashboard</Link>
          </div>

          <div className="footer-links-col">
            <strong>Legal & Support</strong>
            <a href="https://veggie.in/support" target="_blank" rel="noreferrer">Help Center</a>
            <a href="https://veggie.in/privacy" target="_blank" rel="noreferrer">Privacy Policy</a>
            <a href="https://veggie.in/terms" target="_blank" rel="noreferrer">Terms of Service</a>
          </div>
        </div>

        <div className="footer-bottom-v2">
          <div className="v2-container flex justify-between items-center">
            <p>© {new Date().getFullYear()} VEGGIE AFFILIATE NETWORK. All rights reserved.</p>
            <div className="flex gap-4">
              <span>🔒 Encrypted & SSL Secured</span>
              <span>⚡ Powered by Veggie SaaS</span>
            </div>
          </div>
        </div>
      </footer>
    </main>
  );
};
